install: carthage update --platform iOS
language: swift
os: osx
osx_image: xcode9.3
script:
  xcodebuild -scheme Stylobate -project Stylobate.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=10.0' test
after_success:
  bash <(curl -s https://codecov.io/bash)
